#!/usr/bin/env bash

# hrsync by Daniele Paroli
#
# simple script to backup a directory with rsync detecting moved and renamed files
#
# use it at your own risk, please see README and LICENSE files

# ------------------------------------------------------------
# Backup source and target directory 

Source="/Users/leo/rsync-test/rsync-demo/1-LOCAL"
Target="/Users/leo/rsync-test/rsync-demo/2-REMOTE"

# ------------------------------------------------------------
# Name of shadow directory
Shadow=".rsync_shadow"

# 0) MAKE INITIAL SHADOW DIR ON SOURCE ################################################################

if [ ! -d "$Source/$Shadow" ] ; then
	# first time run: create source shadow
	rsync \
	-a \
	--delete \
	--link-dest="$Source" \
	`# MAKES NEW HLs if unchanged|new files found in Source` \
	--exclude="/$Shadow" \
	`# dont nest the shadow dir in itself` \
	"$Source"/ \
	"$Source/$Shadow"
fi

# 1) SYNC SOURCE>TARGET AND COPY SHADOW DIR ################################################################
	# copies SOURCE files to TARGET
	# also copies the SOURCE SHADOW DIR to the TARGET SHADOW DIR preserving the hard links with -H. it looks for hard linked files in the SOURCE and links the same ones on the TARGET

# do real syncronization
	rsync \
	--progress \
	-axXhHv `# TRANSFERS HLs between files on SOURCE to TARGET, so it transfers the SOURCE/SHADOW dir` \
	--stats \
	--no-inc-recursive \
	--numeric-ids \
	--delete \
	--delete-after \
	"$Source"/ \
	"$Target"
	# NOTE: this DOES take time to transfer 1st time. 
	# completely transfers all SOURCE to TARGET including shadow dir of hard links with -H

# status=$?

# # 2) UPDATE/MIRROR SHADOW TO CURRENT FILESTRUCTURE ################################################################

# update source shadow directory - SAME AS INITIAL STEP
	rsync \
	-a \
	--delete \
	--link-dest="$Source" \
	`# unchanged files are hard linked from here to SOURCE SHADOW (destination)` \
	--exclude="/$Shadow" \
	`# dont nest shadow dir in itself` \
	"$Source"/ \
	"$Source/$Shadow"
	# mirror SOURCE_SHADOW from SOURCE, deleting stuff from SOURCE_SHADOW (making new HL mirror of SOURCE), and linking SOURCE as source of finding hard linked files for renames... i think i have that right
	# FIXME: link dest is not on dest?

# update target shadow directory
	rsync \
	-a \
	--delete \
	--link-dest="$Target" \
	--exclude="/$Shadow" \
	"$Target/" \
	"$Target/$Shadow"

# NOW JUST RENAME SOME FILES AND RUN AGAIN AND IT SHOULD JUST UPDATE NAMES ON TARGET INSTEAD OF TRANSFERRING THE ENTIRE FILE AGAIN
